# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HighPowerBear
email: info@highpowerbear.com
github: https://github.com/robertkolar
twitter: https://twitter.com/highpowerbear
description: > # this means to ignore newlines until "baseurl:"
  Financial software solutions
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://highpowerbear.com" # the base hostname & protocol for your site
chartsurl: "http://charts.highpowerbear.com"
permalink: /:categories/:short_year:month:day/
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: highpowerbear
      category: market
      layout: market-post
      default-interval: daily
      image-suffix: png
symbols: {
  SPY:  "SPY - S&P 500 ETF",
  IWM:  "IWM - Russell 2000 ETF",

  EURUSD: "EURUSD - Euro to US Dollar",
  GBPUSD: "GBPUSD - British Pound to US Dollar",
  AUDUSD: "AUDUSD - Australian Dollar to US Dollar",
  USDJPY: "USDJPY - US Dollar to Japanese Yen",
  USDCHF: "USDCHF - US Dollar to Swiss Franc",
  USDCAD: "USDCAD - US Dollar to Canadian Dollar",

  TLT:  "TLT - Treasury Bond ETF",
  GLD:  "GLD - Gold ETF",
  USO:  "USO - Crude Oil ETF",
  WTIC: "WTIC - Light Crude Oil Spot",
  FXE:  "FXE - Euro Currency ETF",
  DBA:  "DBA - Agriculture ETF",
}

# Build settings
markdown: kramdown
future: true